export enum DocumentType {
  RG_FRONT = "RG_FRONT",
  RG_BACK = "RG_BACK",
  RG_FULL = "RG_FULL",
  CNH_FRONT = "CNH_FRONT",
  CNH_BACK = "CNH_BACK",
  CNH_FULL = "CNH_FULL",
  CRLV = "CRLV",
  RNE_FRONT = "RNE_FRONT",
  RNE_BACK = "RNE_BACK",
  OTHERS = "OTHERS"
}
